install: git clone https://github.com/sstephenson/bats.git
script: PATH="./bats/bin:$PATH" test/run && ( cd plugins/python-build bats ${CI:+--tap} test )
language: c
env:
  - PYENV_NATIVE_EXT=
  - PYENV_NATIVE_EXT=1
